### ISSUE TITLE
User should have control over date format and title line

### ISSUE THREAD

**Issue by LenaicTerrier** [JakeRoggenbuck/Journal.vim#3]
It would be nice for the users to be able to control the date format use in the filename and the line printed at the top of files. Also, this test could be also controlled by the user.

For example : I could want to have iso looking dates (`%Y-%m-%d`) with a markdown *title 1* in my first line (`# Journal : {date}`). Which would make files like : `journal_2023-02-03.md` with the first line being `# Jounal : 2023-02-03`.

This feature is useful since the default date format is localized and the printed line is not, which is weird when the locale is something else than english.

I suggest adding two more config variables : 
- `g:journals_date_format` which defaults at `%b-%d-%Y`
- `g:journals_title_template` which defaults at `Journal entry {date}`

I've made the changes on my computer, I can post a pull request soon if that something you would be interested in.

**Comment by JakeRoggenbuck** [comment]
Yes! That would be an amazing feature!
